# Generated by Django 3.0.5 on 2020-06-04 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_auto_20200530_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewers',
            field=models.ManyToManyField(related_name='viewers', through='forum.PostViewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
