# Generated by Django 3.0.5 on 2020-05-21 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='parent',
        ),
        migrations.AddField(
            model_name='branch',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный'),
        ),
        migrations.AddField(
            model_name='branch',
            name='parent_forum',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.Forum', verbose_name='родительский форум'),
        ),
        migrations.AddField(
            model_name='forum',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_branch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='children_posts', to='forum.Branch', verbose_name='родительская ветка'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_forum',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='children_posts', to='forum.Forum', verbose_name='родительский форум'),
        ),
        migrations.AddField(
            model_name='post',
            name='parent_thread',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.Thread', verbose_name='родительский элемент'),
        ),
        migrations.AddField(
            model_name='thread',
            name='parent_branch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.Branch', verbose_name='родительская ветка'),
        ),
        migrations.AddField(
            model_name='thread',
            name='parent_forum',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='children_threads', to='forum.Forum', verbose_name='родительский форум'),
        ),
        migrations.CreateModel(
            name='ThreadLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='forum.Thread', verbose_name='Тема')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
                'unique_together': {('thread', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='forum.Post', verbose_name='Пост')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='threadLike', through='forum.PostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(related_name='postLike', through='forum.ThreadLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
