# Generated by Django 3.0.7 on 2020-07-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200604_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='название'),
        ),
    ]
