# Generated by Django 3.0.7 on 2020-07-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200718_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadlike',
            options={'verbose_name': 'мнение', 'verbose_name_plural': 'мнения'},
        ),
    ]
