# Generated by Django 3.0.7 on 2020-08-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200727_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=20, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='название'),
        ),
    ]
