# Generated by Django 3.0.5 on 2020-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20200605_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/img/default_avatar.png', upload_to='images/'),
        ),
    ]
