# Generated by Django 3.0.5 on 2020-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20200605_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/default_avatar.png', upload_to='images/avatars/'),
        ),
    ]
