# Generated by Django 3.0.7 on 2020-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20200606_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='displayed_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
