# Generated by Django 3.0.7 on 2020-07-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_customuser_displayed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='images/avatars/default_avatar.png', upload_to='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='displayed_name',
            field=models.CharField(max_length=40),
        ),
    ]
