# Generated by Django 3.0.7 on 2020-07-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20200708_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='displayed_name',
            new_name='displayed',
        ),
    ]
