# Generated by Django 3.0.7 on 2020-07-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_customuser_foreign_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foreign_avatar_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
