# Generated by Django 3.0.7 on 2020-07-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20200728_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foreign_avatar_url',
            field=models.URLField(null=True),
        ),
    ]
