# Generated by Django 3.0.7 on 2020-07-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_auto_20200728_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='displayed',
            field=models.CharField(max_length=40, unique=True, verbose_name='отоброжаемое имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foreign_avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='аватар из стороних источников'),
        ),
    ]
