# Generated by Django 3.0.7 on 2020-07-30 00:56

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_auto_20200728_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='images/default_avatar.png', upload_to=authorization.models.generate_avatar_path, verbose_name='аватар'),
        ),
    ]
