# Generated by Django 3.0.7 on 2020-08-06 01:29

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0016_auto_20200806_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='images/avatars/default_avatar.png', upload_to=authorization.models.generate_avatar_path, verbose_name='аватар'),
        ),
    ]
