# Generated by Django 3.0.7 on 2020-08-28 03:49

import authorization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_auto_20200828_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/default_avatar.png', null=True, upload_to=authorization.models.generate_avatar_path, verbose_name='аватар'),
        ),
    ]
