# Generated by Django 3.0.5 on 2020-05-29 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20200522_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='postLike', through='forum.PostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(related_name='threadLike', through='forum.ThreadLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ThreadViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Thread', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'просмотр',
                'verbose_name_plural': 'просмотры',
                'unique_together': {('thread', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'просмотр',
                'verbose_name_plural': 'просмотры',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.ManyToManyField(related_name='postViewer', through='forum.PostViewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='viewers',
            field=models.ManyToManyField(related_name='threadViewer', through='forum.ThreadViewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
